services:
  - type: web
    name: flask-plot
    env: docker
    repo: https://github.com/your-username/your-repo-name # Replace with your GitHub repo
    region: oregon
    plan: free
    branch: chapter-3-Setting-Automation
    healthCheckPath: /
    dockerfilePath: ./flask_app/Dockerfile
    rootDir: flask_app
    startCommand: gunicorn --bind 0.0.0.0:80 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production

